services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: micro_service_users_php
    depends_on:
      - mariadb
    ports:
      - 80:80
    volumes:
      - .:/var/www/html

  mariadb:
    image: mariadb:10.6.20
    container_name: micro_service_users_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: micro_service_users
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: micro_service_users_phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8080:80
volumes:
  mariadb_data:


