services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: micro_service_posts_php
    depends_on:
      - mariadb
    ports:
      - 81:80
    volumes:
      - .:/var/www/html

  mariadb:
    image: mariadb:10.6.20
    container_name: micro_service_posts_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: micro_service_posts
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3307:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: micro_service_posts_phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8081:80
volumes:
  mariadb_data:


